# Generated by Django 2.0.2 on 2018-02-23 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='', max_length=100)),
                ('descendants', models.IntegerField(default=0)),
                ('story_id', models.IntegerField()),
                ('score', models.IntegerField(default=0)),
                ('text', models.TextField(default='')),
                ('time', models.IntegerField(default=0)),
                ('title', models.CharField(default='', max_length=100)),
                ('type', models.CharField(default='', max_length=100)),
                ('category_name', models.CharField(default='', max_length=100)),
                ('url', models.URLField()),
                ('category_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='news.Category')),
            ],
            options={
                'verbose_name_plural': 'Stories',
            },
        ),
    ]
