# Generated by Django 2.0.2 on 2018-02-23 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='category_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='news.Category'),
        ),
        migrations.AlterField(
            model_name='story',
            name='url',
            field=models.CharField(default='', max_length=100),
        ),
    ]
