# Generated by Django 2.0.2 on 2018-02-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20180223_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='url',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
