# Generated by Django 2.0.2 on 2018-02-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20180223_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='author',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='descendants',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='score',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='story_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='text',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='time',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='type',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
